version: "3"

services:
  server:
    build: server
    container_name: jserver
    entrypoint: /bin/bash
    environment:
      PYTHONPATH: .
      ENVIRONMENT: development
      FLASK_ENV: development
      FLASK_APP: server.views
    ports:
      - 5002:5000
    stdin_open: true
    volumes:
      - ./server/:/app
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build: client
    entrypoint: /bin/bash
    container_name: jclient
    ports:
      - 3002:3000
    stdin_open: true
    volumes:
      - ./client:/client
    logging:
      options:
        max-size: "5m"
        max-file: "3"
