version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    container_name: jserver
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
    ports:
      - 5002:8000
    stdin_open: true
    volumes:
      - ./server/:/app
      - ./common/:/app/common
      - ./storage:/storage
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    entrypoint: yarn start
    container_name: jclient
    ports:
      - 3002:3000
    stdin_open: true
    volumes:
      - ./client:/app
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  gpu-dev:
    build:
      context: .
      dockerfile: ./gpu.dockerfile
    container_name: jgpu-dev
    entrypoint: /bin/bash
    stdin_open: true
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
    volumes:
      - ./gpu:/paperspace
      - ./common:/paperspace/common
      - ./storage:/storage
    device_requests:
      - capabilities:
          - "gpu"
