version: "3.7"

services:
  server:
    build: server
    container_name: jserver
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
    ports:
      - 5002:8000
    stdin_open: true
    volumes:
      - ./server/:/app
      - ./common/:/app/common
      - ./.aws:/root/.aws
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build: client
    entrypoint: /bin/bash
    container_name: jclient
    ports:
      - 3002:3000
    stdin_open: true
    volumes:
      - ./client:/client
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  gpu-dev:
    build: gpu
    container_name: jgpu-dev
#    entrypoint: /bin/bash
    stdin_open: true
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
      TORCH_HOME: /bigmodels
    volumes:
      - ./gpu:/app
      - ./common:/app/common
      - ./.aws:/root/.aws
      - ./bigmodels:/bigmodels
    device_requests:
      - capabilities:
          - "gpu"
