version: "3"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --api=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=tylerrenelle@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    labels:
      # global redirect to https
      - traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.http-catchall.entrypoints=web
      - traefik.http.routers.http-catchall.middlewares=redirect-to-https

      # middleware redirect
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    build: server
    container_name: jserver
    environment:
      ENVIRONMENT: production
      FLASK_ENV: production
      MODULE_NAME: server.views
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.gnothiai.com`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls.certresolver=myresolver
    stdin_open: true
    volumes:
      - ./server/:/app
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build: client
    command: serve -s build -l tcp://0.0.0.0:3000
    container_name: jclient
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`gnothiai.com`,`www.gnothiai.com`,`gnothiapp.com`,`www.gnothiapp.com`)
      - traefik.http.routers.client.entrypoints=websecure
      - traefik.http.routers.client.tls.certresolver=myresolver
      - traefik.http.services.client.loadbalancer.server.port=3000
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./client:/client
