version: "3"
services:
  server:
    build: server
    container_name: jserver
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
      JWT_SECRET_KEY: my jwt secret key
      FLASK_APP: jwtauthtest
      FLASK_ENV: development
    networks:
      - jnet
    ports:
      - 5000:5000
    stdin_open: true
    volumes:
      - ./server/:/app
    links:
      - "db"

  client:
    build: client
#    command: yarn --modules-folder /node_modules start
    command: /bin/bash
    container_name: jclient
    networks:
      - jnet
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./client:/client

  db:
    image: postgres
    container_name: jdb
    networks:
      - jnet
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mypassword

networks:
  jnet:
