version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./server.dockerfile
    container_name: jserver
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
    ports:
      - 5002:8000
    stdin_open: true
    volumes:
      - ./server/:/app
      - ./common/:/app/common
      - ./storage:/storage
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    entrypoint: /bin/bash
    container_name: jclient
    ports:
      - 3002:3000
    stdin_open: true
    volumes:
      - ./client:/app
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  gpu-dev:
    build:
      context: .
      dockerfile: ./gpu.dockerfile
    container_name: jgpu-dev
    entrypoint: /bin/bash
    stdin_open: true
    restart: unless-stopped
    environment:
      ENVIRONMENT: development
    ports:
      - 8888:8888
    volumes:
      - ./gpu:/paperspace
      - ./common:/paperspace/common
      - ./storage:/storage
      - ./ml-tools:/ml-tools
    device_requests:
      - capabilities:
          - "gpu"

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: nPXtAX5rCvnsBf2PYh1s
    volumes:
      - ./storage/gnothidb:/var/lib/postgresql/data
    ports:
      - 5432:5432
