version: "3"
services:
  server:
    build: server
    container_name: jserver
    environment:
      ENVIRONMENT: production
      FLASK_ENV: production
      MODULE_NAME: server.views
    ports:
      - 5001:5000
    stdin_open: true
    volumes:
      - ./server/:/app
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  server-dev:
    build: server
    container_name: jserver-dev
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
      FLASK_ENV: development
      FLASK_APP: server
    ports:
      - 5002:5000
    stdin_open: true
    volumes:
      - ./server/:/app
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build: client
    command: serve -s build -l tcp://0.0.0.0:3001
    container_name: jclient
    ports:
      - 80:3001
      - 3002:3002
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./client:/client