version: "3"
services:
  server:
    build: server
    container_name: jserver
    entrypoint: flask run --host=0.0.0.0
    environment:
      ENVIRONMENT: production
      FLASK_ENV: production
      FLASK_APP: jwtauthtest
    ports:
      - 5001:5000
    stdin_open: true
    volumes:
      - ./server/:/app

  server-dev:
    build: server
    container_name: jserver-dev
#    entrypoint: flask run --host=0.0.0.0
    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
      FLASK_ENV: development
      FLASK_APP: jwtauthtest
    ports:
      - 5002:5000
    stdin_open: true
    volumes:
      - ./server/:/app

  client:
    build: client
    command: serve -s build -l tcp://0.0.0.0:3001
    container_name: jclient
    ports:
      - 3001:3001
      - 3002:3002
    stdin_open: true
    volumes:
      - ./client:/client