version: "3"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --api=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      #- --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.myresolver.acme.email=tylerrenelle@gmail.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  server:
    image: lefnire/gnothi:server-0.0.1
    container_name: jserver
    environment:
      ENVIRONMENT: production
      ACCESS_LOG: ""
    labels:
      - traefik.enable=true
      - traefik.http.routers.server.rule=Host(`api.gnothiai.com`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls.certresolver=myresolver
    stdin_open: true
    volumes:
      - ./storage:/storage
    #  - ./server/:/app
    #  - ./common/:/app/common
    restart: unless-stopped
    logging:
      options:
        max-size: "5m"
        max-file: "3"

  client:
    build:
      context: .
      dockerfile: ./client.dockerfile
    command: serve -s build -l tcp://0.0.0.0:80
    container_name: jclient
    labels:
      - traefik.enable=true

      # redirect http->https. TODO find global https redirect solution
      - traefik.http.middlewares.ssl-redir.redirectscheme.scheme=https
      - traefik.http.middlewares.ssl-redir.redirectscheme.permanent=true
      - traefik.http.routers.client80.middlewares=ssl-redir

      - traefik.http.routers.client80.rule=Host(`gnothiai.com`,`www.gnothiai.com`,`gnothiapp.com`,`www.gnothiapp.com`)
      - traefik.http.routers.client80.entrypoints=web
      #- traefik.http.services.client80.loadbalancer.server.port=80

      - traefik.http.routers.client443.rule=Host(`gnothiai.com`,`www.gnothiai.com`,`gnothiapp.com`,`www.gnothiapp.com`)
      - traefik.http.routers.client443.entrypoints=websecure
      - traefik.http.routers.client443.tls.certresolver=myresolver
      - traefik.http.services.client443.loadbalancer.server.port=80

      # redirect gnothiapp.com
      - traefik.http.middlewares.redir-gnothi.redirectregex.regex=^(.*)gnothiapp.com(.*)
      - traefik.http.middlewares.redir-gnothi.redirectregex.replacement=https://gnothiai.com
      - traefik.http.routers.client443.middlewares=redir-gnothi
      
    stdin_open: true
    restart: unless-stopped
    #volumes:
    #  - ./client:/app
    logging:
      options:
        max-size: "5m"
        max-file: "3"
