version: "3"
services:
  server:
    build: server
    container_name: jserver
    entrypoint: ./run.sh
#    entrypoint: /bin/bash
    environment:
      ENVIRONMENT: development
      JWT_SECRET_KEY: my jwt secret key
      FLASK_APP: jwtauthtest
      FLASK_ENV: development
    networks:
      - jnet
    ports:
      - 5001:5000
    stdin_open: true
    volumes:
      - ./server/:/app
    links:
      - "db"
      - "mysqldb"

  client:
    build: client
    command: yarn start
#    command: /bin/bash
    container_name: jclient
    ports:
      - 3001:3000
    stdin_open: true
    volumes:
      - ./client:/client

  db:
    image: postgres
    container_name: jdb
    networks:
      - jnet
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: mypassword

  mysqldb:
    image: mysql
    container_name: mysqldb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
    networks:
      - jnet
    ports:
      - 3307:3306

networks:
  jnet:
