version: "3.7"

services:
  gpu:
    build:
      context: .
      dockerfile: gpu.dockerfile
    container_name: jgpu
    restart: unless-stopped
    volumes:
      - ./gpu:/paperspace
      - ./common:/paperspace/common
      - ./sotrage:/storage
    device_requests:
      - capabilities:
          - "gpu"
    logging:
      options:
        max-size: "5m"
        max-file: "3"
