version: "3.7"

services:
  gpu:
    image: lefnire/gnothi:gpu-0.0.1
    container_name: jgpu
    restart: unless-stopped
    volumes:
      - ./storage:/storage
    device_requests:
      - capabilities:
          - "gpu"
    logging:
      options:
        max-size: "5m"
        max-file: "3"
