version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "127.0.0.1:53:53"                # only required for Pro
      - "127.0.0.1:53:53/udp"            # only required for Pro
      - "127.0.0.1:443:443"              # only required for Pro
      - "127.0.0.1:4510-4530:4510-4530"  # only required for Pro
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4571:4571"
    environment:
      - SERVICES=acm,apigateway,cloudformation,cloudwatch,cloudwatchlogs,edge,ecs,ec2,efs,es,firehose,iam,kms,kinesis,lambda,route53,rds,s3,secretsmanager,ses,sns,sqs,ssm,stepfunctions,sts
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
      - DOCKER_HOST=unix:///var/run/docker.sock
      # Defaults
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
      # My configs
      #- DEBUG=1
      #- DATA_DIR=./tmp/localstack-tmp
      #- LAMBDA_EXECUTOR=docker-reuse
      #- LAMBDA_REMOTE_DOCKER=false
      #- HOST_TMP_FOLDER=./tmp/localstack-tmp
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
