# https://geshan.com.np/blog/2022/02/mysql-docker-compose/

version: '3.8'
services:
  db:
    image: mysql:5
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=books
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      # That's slick, it just imports the database if it's in this location!
      - /tmp/mldata/db/libgen.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
